@startuml
entity "Товары" as Products <<Коллекция>> {
    + product_id : UUID [PK]
    + name : VARCHAR(225)
    + description : TEXT
    + price : DECIMAL(10,2)
    + quantity : INT
    + category : Object  
}

entity "Категории" as Categories <<Вложенный объект>> {
    + category_id : UUID [PK]
    + name : VARCHAR(100)
    + description : TEXT
}

entity "Корзины" as Baskets <<Коллекция>> {
    + basket_id : UUID [PK]
    + user_id : UUID
    + status : STRING
    + total_price : DECIMAL(10,2)
    + created_at : DATETIME
    + updated_at : DATETIME
    --
    + products : Array<Object> 
}

entity "Заказы" as Orders <<Коллекция>> {
    + order_id : UUID [PK]
    + user_id : UUID
    + order_date : DATETIME
    + status : STRING
    + total_price : DECIMAL(10,2)
    + shipping_address : STRING
    + payment_method : STRING
    --
    + products : Array<Object>  
    + delivery : Object  
}

entity "Транзакции" as Transactions <<Вложенный объект>> {
    + transaction_id : UUID [PK]
    + order_id : UUID
    + transaction_date : DATETIME
    + amount : DECIMAL(10,2)
    + status : STRING
    + transaction_type : STRING
}

entity "Платежи" as Payments <<Коллекция>> {
    + payment_id : UUID [PK]
    + order_id : UUID
    + payment_date : DATETIME
    + amount : DECIMAL(10,2)
    + status : STRING
    + payment_method : STRING
}

entity "Склад" as Warehouse <<Коллекция>> {
    + warehouse_id : UUID [PK]
    + name : STRING
    + location : STRING
}

entity "Пользователи" as Users <<Коллекция>> {
    + user_id : UUID [PK]
    + name : STRING
    + email : STRING
    + phone : STRING
    + registration_date : DATETIME
    + role : STRING  
    + permissions : STRING 
}

entity "Доставка" as Delivery <<Вложенный объект>> {
    + delivery_id : UUID [PK]
    + order_id : UUID
    + delivery_date : DATETIME
    + delivery_status : STRING 
    + delivery_method : STRING
}

entity "Собственная доставка" as OwnDelivery <<Вложенный объект>> {
    + delivery_id_own : UUID [PK]
    + delivery_address_own : STRING
    + tracking_number_own : STRING
    + provider_name_own : STRING 
}

entity "Доставка через поставщика" as PartnerDelivery <<Вложенный объект>> {
    + delivery_id_partner : UUID [PK]
    + provider_name_partner : STRING 
    + tracking_number_partner : STRING 
    + delivery_address_partner : STRING
}

Users *-- Products : выбирает
Products *-- Categories : принадлежит
Baskets *-- Products : находится
Orders *-- Baskets : создает
Orders *-- Warehouse : проверяется
Orders *-- Payments : оплачивается
Payments *-- Transactions : подтверждается
Orders *-- Delivery : доставляется
Delivery *-- OwnDelivery : собственная
Delivery *-- PartnerDelivery : через посредника

@enduml