@startuml
!define Document(name) class name << (D,#FFAAAA) >>
!define Ref <<Ref>> 

Document(Товар) {
  +product_id: int
  +name: string
  +description: string
  +price: decimal
  +quantity: int
  +category: CategoryRef
}

Document(Категория) {
  +category_id: int
  +name: string
  +description: string
}

Document(Корзина) {
  +basket_id: int
  +user_id: int
  +status: string
  +total_price: decimal
  +created_at: datetime
  +updated_at: datetime
  +items: List<ProductRef> 
}

Document(Заказ) {
  +order_id: int
  +user_id: int
  +order_date: datetime
  +status: string
  +total_price: decimal
  +shipping_address: string
  +payment_method: string
  +delivery: DeliveryRef  
  +items: List<ProductRef> 
}

Document(Транзакция) {
  +transaction_id: int
  +order_id: int
  +transaction_date: datetime
  +amount: decimal
  +status: string
  +transaction_type: string
}

Document(Платеж) {
  +payment_id: int
  +order_id: int
  +payment_date: datetime
  +amount: decimal
  +status: string
  +payment_method: string
}

Document(Склад) {
  +warehouse_id: int
  +name: string
  +location: string
}

Document(Остатки_на_складе) {
  +stock_id: int
  +warehouse_id: int
  +product_id: int
  +quantity: int
}

Document(Пользователь) {
  +user_id: int
  +name: string
  +email: string
  +phone: string
  +registration_date: datetime
  +last_login: datetime
  +role: string  
  +permissions: string
  +baskets: List<BasketRef>
  +orders: List<OrderRef> 
}

Document(Доставка) {
  +delivery_id: int
  +order_id: int
  +delivery_date: datetime
  +delivery_status: string 
  +delivery_method: string
}

Document(Собственная_доставка) {
  +delivery_id_own: int
  +delivery_address_own: string
  +tracking_number_own: string
  +provider_name_own: string
}

Document(Доставка_через_поставщика) {
  +delivery_id_partner: int
  +provider_name_partner: string
  +tracking_number_partner: string
  +delivery_address_partner: string
}

Категория ||--o{ Товар
Корзина ||--o{ Товар
Пользователь ||--o{ Корзина
Пользователь ||--o{ Заказ
Заказ ||--o{ Транзакция
Платеж ||--o{ Заказ
Склад ||--o{ Остатки_на_складе
Остатки_на_складе }o--|| Товар
Заказ ||--o{ Доставка
Доставка ||--o{ Собственная_доставка
Доставка ||--o{ Доставка_через_поставщика

@enduml