openapi: 3.0.0
info:
  title: E-Commerce API
  version: 1.0.0
  description: API для управления товарами, заказами и пользователями
servers:
  - url: https://api.example.com/v1

tags:
  - name: products
    description: Информация о товарах
  - name: users
    description: Информация о пользователях

paths:
  /login:
    post:
      tags:
        - users
      summary: Вход в систему, получение токенов
      description: При успешном входе выдаются токены (access и refresh).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  example: "admin"
                  assword:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Успешный вход, получение токенов
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /refresh:
    post:
      tags:
        - users
      summary: Обновление access-токена
      description: Использует refresh-токен для получения нового access-токена.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Новый access-токен
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string

  /products:
    get:
      tags:
        - products
      summary: Получить список товаров
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список товаров

  /users:
    get:
      tags:
        - users
      summary: Получить список пользователей
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список пользователей

  /users/{user_id}:
    get:
      tags:
        - users
      summary: Получить информацию о пользователе
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Данные о пользователе

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
