@startuml
|Пользователь|
start
:Выбор товара;
:Корректировка колличества товаров;
:Оформление заказа;
|Заказы|
:Поступление заявки на формирование заказа;
|Склад|
:Запраос данных о заказе;
:Проверка наличия товара;

    if (товар в наличии?) then (нет)
    |Пользователь|    
    :Уведомление об отсутствии товара;
    end
  
    else (да)
    |Склад|
    :Подтверждение резерва;
    endif  

|Заказы|
:Публикация события о резервировании заказа;
:Запрос информацию о способе оплаты заказа;
|Пользователь|
:Выбор способ оплаты и инициирует платеж;
|Платежи|
:Запрос на оплату заказа;

    if (Оплата прошла?) then (нет)
    |Пользователь|    
    :Уведомление об отклонении оплаты;
    end
  
    else (да)
    |Платежи|
    :Подтверждение оплаты;
    endif     

|Заказы|
:Обновляет статус заказа на "оплачен";
|Заказы|
:Запрос на оформление доставки;
|Доставка|
:Формирование заявки на доставку;
:Информирование о доставке;
|Пользователь|
:Уведомление о доставке заказа;

stop

@enduml